/*
# Copyright 2023 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/

config {
    type: "view",
    name: dataform.projectConfig.vars.customerName,
    schema: dataform.projectConfig.vars.testADSchema,
    tags: ["customer"],
    dependencies: "cust_name_check"
}

select
    cust_dtl_vw.col,
    cust_vw.col2,
    cust_vw2.col3,
    cust_dtl_vw.region
from ${dataform.projectConfig.vars.z0015_cust_dtl_vw} cust_dtl_vw
    inner join ${dataform.projectConfig.vars.z0014_cust_vw} cust_vw
        on cust_dtl_vw.col = cust_vw.col
    left join ${dataform.projectConfig.vars.z0710_cust_vw} cust_vw2
        on cust_vw.col2 = cust_vw2.col2
${dataform.projectConfig.vars.cust_where_clause}
