/*
# Copyright 2023 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/

config {
    type: "operations",
    tags: ["data_lake"],
    dependencies: ["ddl"]
}

-- MEDIUM: NEEDS AT LEAST ACCESS_LEVEL = 1 ELSE HASHED
-- HIGH: NEEDS AT LEAST ACCESS_LEVEL = 2 ELSE NULL

CREATE FUNCTION IF NOT EXISTS ${dataform.projectConfig.defaultSchema}.dynamic_masking(tbl STRING, col STRING, value ANY TYPE)
RETURNS STRING AS (
  CASE
    WHEN (SELECT min(um.access_level) FROM dl_prod_dataset.policy_tags_export pte INNER JOIN dl_prod_dataset.user_metadata um ON um.user_id = SESSION_USER() WHERE pte.table = tbl AND pte.column = col AND pte.tag_id LIKE '%7257713510944033933' GROUP BY pte.column, um.user_id) < 1 THEN TO_HEX(SHA256(value))
    WHEN (SELECT min(um.access_level) FROM dl_prod_dataset.policy_tags_export pte INNER JOIN dl_prod_dataset.user_metadata um ON um.user_id = SESSION_USER() WHERE pte.table = tbl AND pte.column = col AND pte.tag_id LIKE '%5856199489217991922' GROUP BY pte.column, um.user_id) < 2 THEN NULL
    ELSE value
END)
;
