/*
# Copyright 2023 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/

config {
    type: "view",
    name: dataform.projectConfig.vars.retailAccountName,
    schema: dataform.projectConfig.vars.testADSchema,
    tags: ["retail_account"],
    dependencies: ["retail_acct_name_check"]
}

select
    acct_dtl_vw.col,
    acct_vw.col2,
    xref.col3,
    acct_dtl_vw.region
    ${dataform.projectConfig.vars.ra_addtnl_col_lst}
from ${dataform.projectConfig.vars.z0015_acct_dtl_vw} acct_dtl_vw
    inner join ${dataform.projectConfig.vars.z0014_acct_vw} acct_vw
        on acct_dtl_vw.col = acct_vw.col
    left join ${dataform.projectConfig.vars.z0710_acct_xref_vw} xref
        on acct_vw.col2 = xref.col2
${dataform.projectConfig.vars.retail_where_clause}
