/*
# Copyright 2023 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/

config {
    type: "view",
    name: dataform.projectConfig.vars.salesName,
    schema: dataform.projectConfig.vars.testADSchema,
    tags: ["sales"],
    dependencies: "sales_name_check"
}

select
    sales_dtl_vw.col,
    sales_vw.col2,
    sales_dtl_vw.region
from ${dataform.projectConfig.vars.z0015_sales_dtl_vw} sales_dtl_vw
    inner join ${dataform.projectConfig.vars.z0014_sales_vw} sales_vw
        on sales_dtl_vw.col = sales_vw.col
${dataform.projectConfig.vars.sales_where_clause}
